leantime:
  image: leantime/leantime:latest
  container_name: leantime
  restart: unless-stopped
  ports:
    - "8080:8080"
  networks:
    - leantime-net
  environment:
    LEAN_DB_HOST: mysql_leantime
    LEAN_DB_USER: admin
    LEAN_DB_PASSWORD: 321.qwerty
    LEAN_DB_DATABASE: leantime
    LEAN_EMAIL_RETURN: changeme@local.local
